### ISSUE TITLE
Document an XML Namespace URL

### ISSUE THREAD

**Issue by pioto** [heneke/thymeleaf-extras-togglz#4]
So that my IDE isn't sad, it'd be nice to have a documented XML Namespace URL to use.

For extra credit, full support for the Eclipse plugin would be great: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin#adding-content-assist-for-your-dialect

**Comment by heneke** [comment]
Looks like a feasible request. Will try to implement this within a week.

**Comment by pioto** [comment]
Awesome, thanks.

If you can't get to it, I'll see if I can put together something and create a pull request within the next few weeks.

**Comment by pioto** [comment]
How about just using this? https://github.com/heneke/thymeleaf-extras-togglz

I don't think any code change is required, just a documentation update to use something like this to your `<html>` tag:

    xmlns:togglz="https://github.com/heneke/thymeleaf-extras-togglz"

That seems to be sufficient to silence the warnings in Eclipse, at least...
