### ISSUE TITLE
Thymeleaf 3 support

### ISSUE THREAD

**Issue by php-coder** [heneke/thymeleaf-extras-togglz#8]
When I'm trying to use thymeleaf-extras-togglz with Thymeleaf 3.0.0, my app fails with exception `java.lang.ClassNotFoundException: org.thymeleaf.dialect.IExpressionEnhancingDialect`.

Do you have plans on adding support for Thymeleaf 3.0.0?

**Comment by heneke** [comment]
That will need revert major changes. Thymeleaf 2 and 3 are not binary compatible.

**Comment by heneke** [comment]
Give it a try with 2.0.0-SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots/

**Comment by php-coder** [comment]
Thank you! I definitely will try it in 3 weeks.

**Comment by php-coder** [comment]
I can confirm that it works with Thymeleaf 3.0.2.RELEASE. Thank you!

Now I'm waiting for release :)

**Comment by heneke** [comment]
Released to central.
